/**********************************************************************************
* @author       María Dolores Sánchez Meroño - mdolores.sanchez@iecisa.com
* @date         04/11/2019
* @group        Constantes 
* @description  Constantes class for CESS
* @Revision 
**********************************************************************************/

public class CESS_Constantes {

    //CESS
    /* CESS separator*/
    public static final String CESS_SEP = ',';
    /* String for SUCCESS_DELETE_CTI*/
    public static final String SUCCESS_DELETE_CTI = 'Eliminación exitosa';
    /* String for PDT_DELETE_CTI*/
    public static final String PDT_DELETE_CTI = 'Pendiente de eliminar';
    /* String for New State Lead*/
    public static final String LEAD_NEW_STATUS = 'New';
    /* String for No Qualified State*/
    public static final String LEAD_UNQUALIFIED_STATUS = 'Unqualified';
    /* String for result Duplicado*/
    public static final String LEAD_DUPLICADO_RESULT = 'Duplicado';
    /* String for New State Lead*/
    public static final String SIN_INT_CTI = 'Sin Integracion';
	/* String for New State Lead*/
    public static final String INT_DELETE_CTI_SUCCESS = 'SUCCESS';
}