/**********************************************************************************
* @author       Aaron Dominguez Sanchez - aaron.sanchez@salesforce.com
* @date         08/07/2019
* @group        Test
* @description  Test class to test the CESS_AllCESSDataLXCtrlTest class
* @Revision
**********************************************************************************/
@isTest
public class CESS_ConsultaCESSFromLeadDtoTest {

    @IsTest static void testDto() {

        Test.startTest();
            CESS_ConsultaCESSFromLeadDto dto = new CESS_ConsultaCESSFromLeadDto();
        Test.stopTest();
    }

}